import os
import base64
from pathlib import Path

def sync():
    # Yollar
    base_dir = Path(__file__).parent.parent
    agent_dir = base_dir / 'agent'
    src_dir = base_dir / 'installer' / 'src'
    target_file = src_dir / 'embedded_files.py'

    # Build edilmiş agent EXE'sini bul
    agent_exe = agent_dir / 'dist' / 'IntelAudioService.exe'

    print(f"Ashfir Senkronizasyonu başlatıldı...")
    
    if not agent_exe.exists():
        print(f"HATA: {agent_exe} bulunamadı! Önce agent'ı build etmelisiniz.")
        return

    content = ['"""\nGenerated by sync_embedded.py - DO NOT EDIT MANUALLY\n"""\n']

    # 1. Ashfir EXE (Base64)
    print(f"Gömülüyor: {agent_exe.name} -> ASHFIR_EXE")
    exe_data = agent_exe.read_bytes()
    exe_b64 = base64.b64encode(exe_data).decode('utf-8')
    content.append(f'ASHFIR_EXE = "{exe_b64}"\n')



    target_file.write_text('\n'.join(content), encoding='utf-8')
    print(f"BAŞARILI: {target_file} güncellendi.")

if __name__ == '__main__':
    sync()
